# Site settings
title: Hannwi's Tech Blog
email: entraiger@korea.ac.kr
description: 공부한 기술 내용을 기록하는 블로그입니다.
baseurl: ""
lang: "ko"
url: "https://hannwi.github.io"
twitter_username:
github_username: hannwi
disqus_username:

# Theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dirt"

# Author
author:
  name: "Hannwi"
  avatar: "/assets/images/owl.jpg"
  bio: "공부한 기술 내용을 기록하는 블로그입니다."
  github: "hannwi"
  email: "entraiger@korea.ac.kr"

# Defaults
defaults:
  - scope:
      path: ""      # 모든 경로
      type: posts   # _posts/ 의 파일들
    values:
      layout: post  # 이 기본값이 적용됨
      author_profile: true
      read_time: true

# Build settings
markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-include-cache

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"
