# Site settings
title: Hannwi's Technical Blog
email: entraiger@korea.ac.kr
description: Posts technical articles, findings, and know-hows.
baseurl: ""
lang: "en"
url: "https://hannwi.github.io"
twitter_username:
github_username: hannwi
disqus_username:

# Theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

# Author
author:
  name: "Hannwi"
  bio: "Technical blog for lifetime study."
  github: "hannwi"
  email: "entraiger@korea.ac.kr"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true

# Build settings
markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-include-cache

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"
